### ISSUE TITLE
very few deletions call for HMZDelFinder

### ISSUE THREAD

**Issue by snashraf** [BCM-Lupskilab/HMZDelFinder#1]
I have used this HMZDelfinder for 16 Exome Samples and I just got few 5-6 Deletion Calls. Do you have any idea what could be possible reason for this ? I have used TGP bed file provided for you. I assumed that I can use same BED file for all the other analysis.

**Comment by tgambin** [comment]
5-6 deletion is what I would expect from 16 exome samples, so I think it is fine. Please note these are only homozygous and hemizygous deletions and no heterozygous CNVs are reported by this tool.

Of course, you can use TGP bed file but if you have target region bed specific to your exome data it would be better to use such a file.
