### ISSUE TITLE
calcRPKMsFromBAMs() 

### ISSUE THREAD

**Issue by athitheo** [BCM-Lupskilab/HMZDelFinder#8]
Dear Tomasz,

I am trying to test HMZDelFinder on our undiagnosed exome samples. To start with I am not an R expert - trying to learn by using it :). I used the R/3.2 version on slurm clusters and the 1000G example worked fine. When trying to run with R/3.0.1 which you recommend the library data.table is not available on that version. Nevertheless, I am having most probably a memory issue when trying to run the calcRPKMSFromBAMS to create the RPKM files from my data. For the record I used initially 12 exome bam files and then a single one for check. this is the error I get on both cases:

 *** caught segfault ***
address 0x2aaee8021000, cause 'invalid permissions'
*** glibc detected *** /gpfs/buildsets/eb161004/software/R/3.2.3-intel-2016a-libX11-1.6.3/lib64/R/bin/exec/R: free(): invalid next size (normal): 0x00002aaee8002ee0 ***

Any clues on what is going wrong here?
Somethings wrong when the featureCounts function takes place. I tried the command separately for featurecounts and I get the same error. 

Best
Athina

**Comment by tgambin** [comment]
There are some problems with R implementations of featureCounts and I also observed similar errors. 
The workaround is to use a standalone version of featureCounts (http://bioinf.wehi.edu.au/featureCounts/)
Best,
Tomek

**Comment by athitheo** [comment]
Thank you very much I will try it.
